"""Synthesize the 4-second title-card sound, deterministically.

Nothing here is a downloaded sample. Every component is generated by ffmpeg from
an expression, for the same reason the rest of this film is generated rather than
edited: the whole thing has to rebuild from the repo, and a licensed sample in a
gitignored folder is exactly the sort of dependency that dies quietly.

The cue is built to land with the wordmark at 0.80s:

    0.00-0.85  riser      filtered noise + a rising tone, both ramped in on a
                          curve, so the ear is leaning forward at the cut
    0.80       transient  a 60ms noise crack: the attack of the stamp
    0.80       impact     45Hz and 92Hz sines on separate exponential decays,
                          the body of the hit
    0.82       shimmer    a high partial with a slow decay, so the hit has air
    ~3.2       silence    everything has decayed by here, leaving the last 0.8s
                          clean for the film's first line to breathe into

Output is 48kHz stereo WAV, matching what Remotion muxes.

    .venv/Scripts/python video-remotion/scripts/make_intro_sfx.py
"""

from __future__ import annotations

import pathlib
import subprocess

ROOT = pathlib.Path(__file__).resolve().parents[2]
DEST = ROOT / "video-remotion" / "public" / "audio" / "intro_sfx.wav"

HIT = 0.80  # seconds; must match the wordmark's spring in S0Title.tsx
DUR = 4.0
SR = 48000

# Each source is (lavfi description, filter chain applied to it).
SOURCES = [
    # Riser, noise. Ramped in on a power curve rather than linearly, so it
    # accelerates into the hit instead of sliding up at a constant rate.
    (
        f"anoisesrc=d={HIT + 0.05}:c=white:a=0.55:r={SR}",
        f"highpass=f=520,lowpass=f=7000,"
        f"volume=volume='pow(min(1,t/{HIT}),2.6)':eval=frame,"
        f"afade=t=out:st={HIT - 0.02}:d=0.07",
    ),
    # Riser, tone. Quadratic sweep from ~180Hz upward.
    (
        f"aevalsrc='0.22*sin(2*PI*(180+760*t*t)*t)':d={HIT + 0.05}:s={SR}",
        f"volume=volume='pow(min(1,t/{HIT}),3.0)':eval=frame,"
        f"afade=t=out:st={HIT - 0.02}:d=0.07",
    ),
    # Transient: the crack of the stamp landing.
    (
        f"anoisesrc=d=0.09:c=white:a=0.7:r={SR}",
        f"highpass=f=1200,volume=volume='exp(-46*t)':eval=frame,"
        f"adelay={int(HIT * 1000)}|{int(HIT * 1000)}",
    ),
    # Impact: the body. Two sines, two decay rates, so it thumps then rounds off.
    (
        f"aevalsrc='0.95*sin(2*PI*45*t)*exp(-3.0*t)"
        f"+0.5*sin(2*PI*92*t)*exp(-4.4*t)':d=2.4:s={SR}",
        f"adelay={int(HIT * 1000)}|{int(HIT * 1000)}",
    ),
    # Shimmer: air above the hit, so it is not purely a sub thud.
    (
        f"aevalsrc='0.10*sin(2*PI*2350*t)*exp(-2.4*t)"
        f"+0.05*sin(2*PI*3900*t)*exp(-3.1*t)':d=2.2:s={SR}",
        f"adelay={int((HIT + 0.02) * 1000)}|{int((HIT + 0.02) * 1000)}",
    ),
]


def main() -> None:
    DEST.parent.mkdir(parents=True, exist_ok=True)

    cmd: list[str] = ["ffmpeg", "-y", "-loglevel", "error"]
    for src, _ in SOURCES:
        cmd += ["-f", "lavfi", "-i", src]

    chains = [f"[{i}:a]{filt}[s{i}]" for i, (_, filt) in enumerate(SOURCES)]
    mix_in = "".join(f"[s{i}]" for i in range(len(SOURCES)))
    chains.append(
        f"{mix_in}amix=inputs={len(SOURCES)}:duration=longest:normalize=0[mix]"
    )
    # A short echo pair stands in for a room. Cheaper than a convolution reverb
    # and, at this length, indistinguishable.
    chains.append(
        "[mix]aecho=0.5:0.6:55|110:0.28|0.16,"
        "highpass=f=28,"
        "alimiter=limit=0.92:level=disabled,"
        # The mix ends when its longest source has decayed (~3.3s), so pad to
        # the full card length: the asset must be exactly DUR for the clip to
        # line up without the editor having to nudge it.
        f"apad=whole_dur={DUR},atrim=0:{DUR},afade=t=out:st={DUR - 0.25}:d=0.25,"
        "aformat=sample_fmts=s16:sample_rates=48000:channel_layouts=stereo[out]"
    )

    cmd += ["-filter_complex", ";".join(chains), "-map", "[out]", str(DEST)]
    subprocess.run(cmd, check=True)

    probe = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration",
         "-of", "default=nw=1:nk=1", str(DEST)],
        capture_output=True, text=True, check=True,
    )
    print(f"wrote {DEST.relative_to(ROOT)}  {float(probe.stdout.strip()):.3f}s")


if __name__ == "__main__":
    main()
