"""Generate the seed catalog for the demo merchant.

Deterministic by construction -- no randomness, no timestamps -- so the catalog-health and
negotiation numbers in `evidence/` reproduce exactly on any machine.

The catalog is deliberately imperfect. Roughly a fifth of the SKUs carry a real defect of the
kind that shows up in an actual price list: a missing HSN code, a GST rate that is not a real
slab, no unit of measure, stock marked in but counted zero, a cost above the list price. Those
are what the gap validator is for, and a spotless catalog would prove nothing.

    .venv/Scripts/python.exe scripts/make_seed_catalog.py
"""

from __future__ import annotations

import json
from pathlib import Path

from vendable.core.models import Product
from vendable.core.money import rupees

OUT = Path(__file__).resolve().parents[1] / "fixtures" / "merchants" / "acme-fasteners"

# (sku, title, description, list, cost, hsn, gst_bp, unit, moq, stock, age_days, brand, cat)
ROWS: list[tuple] = [
    # --- fasteners: the healthy core of the catalog ---
    (
        "BOLT-M8-40",
        "Hex bolt M8 x 40mm",
        "Hot dip galvanised mild steel hex bolt, 8mm diameter, 40mm length, coarse thread.",
        "12.50",
        "8.00",
        "73181500",
        1800,
        "piece",
        100,
        8000,
        45,
        "Tata",
        "fasteners",
    ),
    (
        "BOLT-M8-60",
        "Hex bolt M8 x 60mm",
        "Hot dip galvanised mild steel hex bolt, 8mm diameter, 60mm length, coarse thread.",
        "15.00",
        "9.60",
        "73181500",
        1800,
        "piece",
        100,
        6200,
        45,
        "Tata",
        "fasteners",
    ),
    (
        "BOLT-M10-50",
        "Hex bolt M10 x 50mm",
        "Zinc plated high tensile hex bolt, 10mm diameter, 50mm length, grade 8.8.",
        "22.00",
        "14.50",
        "73181500",
        1800,
        "piece",
        100,
        4400,
        120,
        "Tata",
        "fasteners",
    ),
    (
        "BOLT-M12-75",
        "Hex bolt M12 x 75mm",
        "Zinc plated high tensile hex bolt, 12mm diameter, 75mm length, grade 8.8.",
        "38.00",
        "25.00",
        "73181500",
        1800,
        "piece",
        50,
        2800,
        200,
        "Tata",
        "fasteners",
    ),
    (
        "NUT-M8",
        "Hex nut M8",
        "Galvanised mild steel hex nut to suit M8 bolts, coarse thread.",
        "3.20",
        "1.90",
        "73181600",
        1800,
        "piece",
        200,
        22000,
        30,
        "Tata",
        "fasteners",
    ),
    (
        "NUT-M10",
        "Hex nut M10",
        "Galvanised mild steel hex nut to suit M10 bolts, coarse thread.",
        "4.80",
        "2.90",
        "73181600",
        1800,
        "piece",
        200,
        18000,
        30,
        "Tata",
        "fasteners",
    ),
    (
        "NUT-M12",
        "Hex nut M12",
        "Galvanised mild steel hex nut to suit M12 bolts, coarse thread.",
        "7.50",
        "4.60",
        "73181600",
        1800,
        "piece",
        200,
        9500,
        210,
        "Tata",
        "fasteners",
    ),
    (
        "WASH-M8",
        "Flat washer M8",
        "Galvanised flat washer, 8mm internal diameter, 1.6mm thick.",
        "1.10",
        "0.60",
        "73182200",
        1800,
        "piece",
        500,
        40000,
        15,
        "Tata",
        "fasteners",
    ),
    (
        "WASH-M10",
        "Flat washer M10",
        "Galvanised flat washer, 10mm internal diameter, 2mm thick.",
        "1.60",
        "0.90",
        "73182200",
        1800,
        "piece",
        500,
        35000,
        15,
        "Tata",
        "fasteners",
    ),
    (
        "WASH-SPR-M8",
        "Spring washer M8",
        "Spring lock washer, 8mm internal diameter, hardened steel.",
        "1.80",
        "1.00",
        "73182100",
        1800,
        "piece",
        500,
        26000,
        190,
        "Tata",
        "fasteners",
    ),
    (
        "SCRW-SD-25",
        "Self drilling screw 25mm",
        "Hex head self drilling screw, 25mm, zinc plated, for sheet metal up to 2mm.",
        "2.40",
        "1.35",
        "73181400",
        1800,
        "piece",
        500,
        30000,
        60,
        "Hilti",
        "fasteners",
    ),
    (
        "SCRW-SD-38",
        "Self drilling screw 38mm",
        "Hex head self drilling screw, 38mm, zinc plated, for sheet metal up to 3mm.",
        "3.10",
        "1.75",
        "73181400",
        1800,
        "piece",
        500,
        24000,
        60,
        "Hilti",
        "fasteners",
    ),
    (
        "ANCH-M10",
        "Wedge anchor M10 x 100",
        "Through-bolt wedge anchor for concrete, 10mm x 100mm, zinc plated.",
        "42.00",
        "27.00",
        "73181500",
        1800,
        "piece",
        50,
        3200,
        95,
        "Hilti",
        "anchors",
    ),
    (
        "ANCH-M12",
        "Wedge anchor M12 x 130",
        "Through-bolt wedge anchor for concrete, 12mm x 130mm, zinc plated.",
        "68.00",
        "44.00",
        "73181500",
        1800,
        "piece",
        50,
        1900,
        95,
        "Hilti",
        "anchors",
    ),
    (
        "ANCH-CHEM",
        "Chemical anchor cartridge 380ml",
        "Two-part styrene-free vinylester resin cartridge for heavy anchoring, 380ml.",
        "620.00",
        "410.00",
        "35069999",
        1800,
        "cartridge",
        6,
        340,
        240,
        "Hilti",
        "anchors",
    ),
    # --- tools: higher value, slower moving ---
    (
        "TOOL-SPN-8",
        "Combination spanner 8mm",
        "Chrome vanadium combination spanner, 8mm, mirror polished.",
        "145.00",
        "92.00",
        "82041110",
        1800,
        "piece",
        10,
        480,
        300,
        "Taparia",
        "tools",
    ),
    (
        "TOOL-SPN-SET",
        "Combination spanner set 8-22mm",
        "Twelve piece chrome vanadium combination spanner set, 8mm to 22mm, in roll pouch.",
        "1850.00",
        "1180.00",
        "82041120",
        1800,
        "set",
        2,
        120,
        330,
        "Taparia",
        "tools",
    ),
    (
        "TOOL-DRL-13",
        "Impact drill 13mm 750W",
        "Reversible impact drill, 13mm chuck, 750W, variable speed, with side handle.",
        "4200.00",
        "2950.00",
        "84672100",
        1800,
        "piece",
        1,
        45,
        150,
        "Bosch",
        "power tools",
    ),
    (
        "TOOL-ANG-4",
        "Angle grinder 100mm 850W",
        "Angle grinder, 100mm disc, 850W, with guard and side handle.",
        "3100.00",
        "2180.00",
        "84672900",
        1800,
        "piece",
        1,
        62,
        150,
        "Bosch",
        "power tools",
    ),
    (
        "TOOL-TAPE-5",
        "Measuring tape 5m",
        "Steel measuring tape, 5m, auto lock, with belt clip.",
        "165.00",
        "98.00",
        "90178000",
        1800,
        "piece",
        20,
        900,
        40,
        "Freemans",
        "tools",
    ),
    (
        "TOOL-PLR-8",
        "Combination plier 8 inch",
        "Insulated combination plier, 8 inch, 1000V rated, chrome vanadium.",
        "310.00",
        "195.00",
        "82032000",
        1800,
        "piece",
        10,
        420,
        85,
        "Taparia",
        "tools",
    ),
    (
        "TOOL-HAM-500",
        "Ball pein hammer 500g",
        "Drop forged ball pein hammer, 500g head, hardwood handle.",
        "285.00",
        "175.00",
        "82055900",
        1800,
        "piece",
        10,
        260,
        275,
        "Taparia",
        "tools",
    ),
    # --- abrasives and consumables ---
    (
        "ABR-CUT-4",
        "Cutting disc 100mm",
        "Reinforced resin bonded cutting disc for metal, 100mm x 1.2mm.",
        "22.00",
        "12.50",
        "68042290",
        1800,
        "piece",
        50,
        5600,
        70,
        "Norton",
        "abrasives",
    ),
    (
        "ABR-GRD-4",
        "Grinding disc 100mm",
        "Depressed centre grinding disc for metal, 100mm x 6mm.",
        "38.00",
        "22.00",
        "68042290",
        1800,
        "piece",
        25,
        3100,
        70,
        "Norton",
        "abrasives",
    ),
    (
        "ABR-FLAP-4",
        "Flap disc 100mm 80 grit",
        "Zirconia flap disc, 100mm, 80 grit, for finishing steel and stainless.",
        "54.00",
        "33.00",
        "68052000",
        1800,
        "piece",
        25,
        2200,
        180,
        "Norton",
        "abrasives",
    ),
    (
        "CONS-WELD-25",
        "Welding electrode 2.5mm 5kg",
        "Mild steel welding electrode, 2.5mm, E6013, five kilogram pack.",
        "690.00",
        "455.00",
        "83112000",
        1800,
        "pack",
        4,
        380,
        55,
        "Esab",
        "consumables",
    ),
    (
        "CONS-TAPE-PVC",
        "PVC insulation tape",
        "Self adhesive PVC electrical insulation tape, 18mm x 20m, black.",
        "18.00",
        "9.50",
        "39191000",
        1800,
        "roll",
        100,
        12000,
        25,
        "Steelgrip",
        "consumables",
    ),
    (
        "CONS-GLOVE-L",
        "Safety gloves large",
        "Nitrile coated cut resistant safety gloves, size large, EN388 rated.",
        "125.00",
        "72.00",
        "62160000",
        1200,
        "pair",
        24,
        1600,
        110,
        "Karam",
        "safety",
    ),
    (
        "CONS-GOGG",
        "Safety goggles clear",
        "Polycarbonate wraparound safety goggles, clear anti-fog lens.",
        "185.00",
        "108.00",
        "90049000",
        1200,
        "piece",
        12,
        740,
        130,
        "Karam",
        "safety",
    ),
    (
        "CONS-HELM",
        "Safety helmet white",
        "HDPE safety helmet with ratchet suspension, IS 2925 certified, white.",
        "340.00",
        "205.00",
        "65061010",
        1200,
        "piece",
        12,
        520,
        220,
        "Karam",
        "safety",
    ),
    # --- plumbing and misc ---
    (
        "PIPE-GI-15",
        "GI pipe 15mm x 6m",
        "Galvanised iron pipe, 15mm nominal bore, six metre length, medium class.",
        "780.00",
        "520.00",
        "73063090",
        1800,
        "length",
        5,
        240,
        100,
        "Jindal",
        "plumbing",
    ),
    (
        "PIPE-GI-25",
        "GI pipe 25mm x 6m",
        "Galvanised iron pipe, 25mm nominal bore, six metre length, medium class.",
        "1320.00",
        "890.00",
        "73063090",
        1800,
        "length",
        5,
        180,
        100,
        "Jindal",
        "plumbing",
    ),
    (
        "PIPE-ELB-15",
        "GI elbow 15mm",
        "Galvanised iron elbow, 15mm, threaded, heavy duty.",
        "45.00",
        "27.00",
        "73079900",
        1800,
        "piece",
        20,
        1400,
        65,
        "Jindal",
        "plumbing",
    ),
    (
        "SEAL-PTFE",
        "PTFE thread seal tape",
        "PTFE thread sealing tape, 12mm x 10m, for threaded pipe joints.",
        "14.00",
        "7.50",
        "39199090",
        1800,
        "roll",
        100,
        9000,
        35,
        "Champion",
        "plumbing",
    ),
    (
        "LUBE-SPR-200",
        "Penetrating spray 200ml",
        "Multipurpose penetrating oil and rust release spray, 200ml aerosol.",
        "215.00",
        "132.00",
        "27101990",
        1800,
        "can",
        12,
        860,
        145,
        "WD-40",
        "consumables",
    ),
]

# SKUs carrying a deliberate, realistic defect. Each entry says what is broken and why that
# happens in the real world, so the gap report is demonstrating something rather than
# punishing a strawman.
DEFECTS: list[tuple] = [
    # sku, title, description, list, cost, hsn, gst, unit, moq, stock, age, brand, cat, why
    (
        "BOLT-M6-25",
        "Hex bolt M6 x 25mm",
        "Zinc plated hex bolt, 6mm diameter, 25mm length.",
        "8.00",
        "5.00",
        "",
        1800,
        "piece",
        200,
        14000,
        50,
        "Tata",
        "fasteners",
        "HSN column was blank in the source sheet",
    ),
    (
        "NUT-M6",
        "Hex nut M6",
        "Zinc plated hex nut to suit M6 bolts.",
        "2.10",
        "1.20",
        "7318l600",
        1800,
        "piece",
        500,
        26000,
        50,
        "Tata",
        "fasteners",
        "OCR read the digit 1 as a lowercase L",
    ),
    (
        "ABR-CUT-7",
        "Cutting disc 180mm",
        "Reinforced resin bonded cutting disc for metal, 180mm x 1.6mm.",
        "62.00",
        "38.00",
        "68042290",
        1700,
        "piece",
        25,
        1800,
        80,
        "Norton",
        "abrasives",
        "GST typed as 17 percent, which is not a slab",
    ),
    (
        "TOOL-SCRW-SET",
        "Screwdriver set 6 piece",
        "Six piece screwdriver set.",
        "420.00",
        "265.00",
        "82054000",
        1800,
        "",
        5,
        380,
        160,
        "Taparia",
        "tools",
        "unit of measure missing, so 420 is ambiguous",
    ),
    (
        "CONS-MASK-N95",
        "N95 mask",
        "Filtering facepiece.",
        "45.00",
        "26.00",
        "63079020",
        500,
        "piece",
        50,
        0,
        400,
        "Venus",
        "safety",
        "marked in stock with zero quantity",
    ),
    (
        "PIPE-GI-40",
        "GI pipe 40mm x 6m",
        "Galvanised iron pipe, 40mm nominal bore, six metre length.",
        "1950.00",
        "2180.00",
        "73063090",
        1800,
        "length",
        5,
        90,
        100,
        "Jindal",
        "plumbing",
        "cost entered per case, price per unit, so it sells at a loss",
    ),
]


def build() -> list[Product]:
    products: list[Product] = []
    for sku, title, desc, price, cost, hsn, gst, unit, moq, stock, age, brand, cat in ROWS:
        products.append(
            Product(
                sku=sku,
                title=title,
                description=desc,
                list_price_paise=rupees(price),
                cost_price_paise=rupees(cost),
                hsn_code=hsn,
                gst_rate_bp=gst,
                unit=unit,
                moq=moq,
                stock_qty=stock,
                stock_age_days=age,
                brand=brand,
                category=cat,
                territories=["IN-KA", "IN-MH", "IN-TN"],
                source_ref="acme-pricelist-2026-q2.pdf",
            )
        )
    for sku, title, desc, price, cost, hsn, gst, unit, moq, stock, age, brand, cat, why in DEFECTS:
        products.append(
            Product(
                sku=sku,
                title=title,
                description=desc,
                list_price_paise=rupees(price),
                cost_price_paise=rupees(cost),
                hsn_code=hsn,
                gst_rate_bp=gst,
                unit=unit,
                moq=moq,
                stock_qty=stock,
                stock_age_days=age,
                brand=brand,
                category=cat,
                territories=["IN-KA", "IN-MH", "IN-TN"],
                source_ref=f"acme-pricelist-2026-q2.pdf ({why})",
            )
        )
    return products


def main() -> None:
    products = build()
    OUT.mkdir(parents=True, exist_ok=True)
    path = OUT / "catalog.json"
    path.write_text(
        json.dumps([p.model_dump(mode="json") for p in products], indent=2, ensure_ascii=False),
        encoding="utf-8",
    )

    from vendable.core.models import catalog_health

    health, gaps = catalog_health(products)
    print(f"wrote {len(products)} SKUs to {path}")
    print(
        f"  transactable: {health.transactable_skus}/{health.total_skus} "
        f"({health.transactable_pct:.0f}%)"
    )
    print(
        f"  gaps: {health.blocking_gaps} blocking, {health.degrading_gaps} degrading, "
        f"{health.advisory_gaps} advisory"
    )
    print("  top 5 by revenue at risk:")
    for gap in gaps[:5]:
        print(f"    {gap}")


if __name__ == "__main__":
    main()
