"""Render `docs/architecture.svg` to a PNG for the pitch video and the submission form.

The SVG is the source of truth and is hand-authored -- it renders on GitHub on its own and
needs no build step. This script exists only because a submission form and a video timeline
want a raster, and a PNG regenerated by hand drifts from the SVG the moment either changes.

    .venv/Scripts/python.exe scripts/render_diagram.py

Uses the Chromium already installed for the console checks. Nothing else in the repo depends
on it, and it touches the network not at all: the SVG has no external references, by design.
"""

from __future__ import annotations

import os
from pathlib import Path

# Set before Playwright launches, same as scripts/verify_console.py. Chromium is ~700 MB and
# C: runs at under 400 MB free.
os.environ.setdefault("PLAYWRIGHT_BROWSERS_PATH", "D:/tmp/pw-browsers")

from playwright.sync_api import sync_playwright

REPO = Path(__file__).resolve().parents[1]
SVG = REPO / "docs" / "architecture.svg"
PNG = REPO / "docs" / "architecture.png"

# Matches the SVG's own viewBox. A device scale of 2 gives a 2480x1800 raster, which stays
# sharp when a 5-minute video scales it to fill a 1080p frame.
WIDTH, HEIGHT, SCALE = 1240, 900, 2


def main() -> int:
    with sync_playwright() as p:
        browser = p.chromium.launch()
        page = browser.new_page(
            viewport={"width": WIDTH, "height": HEIGHT}, device_scale_factor=SCALE
        )
        page.goto(SVG.as_uri())
        page.screenshot(path=str(PNG))
        browser.close()

    print(
        f"{PNG.relative_to(REPO)}  {PNG.stat().st_size:,} bytes  {WIDTH * SCALE}x{HEIGHT * SCALE}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
